name: "neo4j"
description: "stop, clean and start neo4j in order"
inputs:
    stop:
        description: "whether to stop"
        required: true
    clean:
        description: "whether to clean"
        required: true
    start:
        description: "whether to start"
        required: true
    ports:
        description: "ports to run on"
        required: false
        default: "7687"

runs:
    using: "composite"
    steps:
      - if: fromJSON(inputs.stop) || fromJSON(inputs.clean)
        name: unimplemented
        shell: bash
        run: exit 1

      - if: fromJSON(inputs.start) && runner.os != 'Windows'
        name: Create Neo4j Work Directory
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          for port in ${{ inputs.ports }}; do
            instance_dir="./neo4j_instances/$port"
            mkdir -p $instance_dir
            tar -xzf neo4j.tar.gz --strip-components=1 -C $instance_dir
            
            sed -i"" -e "s/#server.http.listen_address=:7474/server.http.listen_address=:1$port/g" $instance_dir/conf/neo4j.conf
            sed -i"" -e "s/#server.bolt.listen_address=:7687/server.bolt.listen_address=:$port/g" $instance_dir/conf/neo4j.conf
            
            chmod +x $instance_dir/bin/neo4j
            chmod +x $instance_dir/bin/neo4j-admin
            
            $instance_dir/bin/neo4j-admin dbms set-initial-password neo4jtest
          
            nohup $instance_dir/bin/neo4j console > neo4j1.log 2>&1 &
            sleep 10
          done
          
      - if: fromJSON(inputs.start) && runner.os == 'Windows'
        name: Create Neo4j Work Directory(Windows)
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          for port in ${{ inputs.ports }}; do
            instance_dir="./neo4j_instances/$port"
            mkdir -p $instance_dir
            powershell -Command "Expand-Archive neo4j.zip -DestinationPath $instance_dir"
            pwd
            dir
            dir $instance_dir
            dir $instance_dir/neo4j-community-5.26.5
            mv $instance_dir/neo4j*/* $instance_dir
            dir $instance_dir
            
            sed -i"" -e "s/#server.http.listen_address=:7474/server.http.listen_address=:1$port/g" $instance_dir/conf/neo4j.conf
            sed -i"" -e "s/#server.bolt.listen_address=:7687/server.bolt.listen_address=:$port/g" $instance_dir/conf/neo4j.conf
          
            $instance_dir/bin/neo4j-admin.bat dbms set-initial-password neo4jtest
          
            start /b $instance_dir/bin/neo4j.bat console
            timeout /t 10
          done

      - name: Check Bolt Ports
        run: |
          for port in ${{ inputs.ports }}; do
            if [[ "$RUNNER_OS" == "Windows" ]]; then
              netstat -ano | findstr $port
            else
              lsof -i :$port || netstat -tuln | grep $port
            fi
          done
        shell: bash