name: "neo4j"
description: "setup neo4j community edition 5.x"

runs:
  using: "composite"
  steps:
    - name: Download and Extract Neo4j
      working-directory: ${{ github.workspace }}
      run: |
        curl -L -o neo4j.tar.gz https://dist.neo4j.org/neo4j-community-5.26.5-unix.tar.gz
        pwd
        ls -a
      shell: bash
