name: "neo4j"
description: "stop, clean and start neo4j in order"
inputs:
    stop:
        description: "whether to stop"
        required: true
    clean:
        description: "whether to clean"
        required: true
    start:
        description: "whether to start"
        required: true
    ports:
        description: "ports to run on"
        required: false
        default: "7687"

runs:
    using: "composite"
    steps:
        - if: fromJSON(inputs.stop) || fromJSON(inputs.clean)
          name: unimplemented
          shell: bash
          run: exit 1

        - if: fromJSON(inputs.start)
          name: Create redis Work Directory
          shell: bash
          working-directory: ${{ github.action_path }}
          run: |
            for port in ${{ inputs.ports }}; do
              instance_dir="${{ github.action_path }}/neo4j_instances/$port"
              
              # 目录结构初始化
              mkdir -p "$instance_dir"/{conf,data,logs,plugins,import}
    
              # 动态生成配置文件
              cat > "$instance_dir/conf/neo4j.conf" << EOF
              server.bolt.enabled=true
              server.bolt.listen_address=:$port
              server.http.enabled=false
              server.directories.data=$instance_dir/data
              server.directories.logs=$instance_dir/logs
              EOF
            done


        - if: fromJSON(inputs.start)
          name: Start redis
          shell: bash
          working-directory: ${{ github.action_path }}
          run: |
            for port in ${{ inputs.ports }}; do
              instance_dir="${{ github.action_path }}/neo4j_instances/$port"
            
              # 启动服务并记录PID
              nohup neo4j-admin server start \
              --config-dir="$instance_dir/conf" \
              --pid-file="$instance_dir/neo4j.pid" > "$instance_dir/logs/startup.log" 2>&1 &
            done
